name: CleanChests
author: BasArts

version: 4.0
description: Clean the server from all kind of stuff

main: CleanChests.main

commands:
  cleanchests:
    permission: Cleanchests.use
    description: A command to Clean the server from some chest inventories stuff
